# Copyright 2020-2023 The MathWorks, Inc

# Workflow to test MATLAB-Proxy while releasing to PyPi
name: Release to PyPI

on:
  release:
    types: [created]

jobs:
  call-run-unit-tests:
    # Call workflow for running node and python tests
    uses: ./.github/workflows/run-unit-tests.yml

  generate-code-coverage:
    # Generates Code coverage and uploads it
    needs: [call-run-unit-tests]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Code Coverage XML
        uses: ./.github/actions/generate-code-coverage


  build_and_publish_pypi:
    needs: call-run-unit-tests
    if: success()
    # windows container is not required here
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.sha}}

      - name: Build and Publish in PyPi
        uses: ./.github/actions/build_and_publish_pypi
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
