# Copyright 2020-2023 The MathWorks, Inc

# Workflow that contains jobs to test MATLAB Proxy
name: Testing MATLAB Proxy Integration

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  # Runs unit tests
  call-run-unit-tests-r000:
    uses: ./.github/workflows/run-unit-tests.yml

  call-run-unit-tests-r001:
    uses: ./.github/workflows/run-unit-tests.yml

  call-run-unit-tests-r002:
      uses: ./.github/workflows/run-unit-tests.yml

  # Runs integration tests
  call-integration-tests:
    uses: ./.github/workflows/run-integration-tests.yml
    secrets: inherit

  # Runs system tests
  call-system-tests:
    uses: ./.github/workflows/run-system-tests.yml
    secrets: inherit
